/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type ProductStatus = "Active" | "Deleted" | "Draft";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Products {
  createdAt: Generated<Timestamp | null>;
  createdBy: string;
  description: string | null;
  fts: Generated<string | null>;
  id: Generated<string>;
  imageUrl: string | null;
  status: Generated<ProductStatus | null>;
  teamId: string;
  title: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface Profiles {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  fullName: string | null;
  id: Generated<string>;
  isOnline: Generated<boolean | null>;
  lastSeen: Generated<Timestamp | null>;
  teamId: string | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface Teams {
  createdAt: Generated<Timestamp | null>;
  id: Generated<string>;
  inviteCode: Generated<string | null>;
  name: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  products: Products;
  profiles: Profiles;
  teams: Teams;
}
